packages:
  - packages/*
  - apps/*

catalog:
  "@orpc/client": ^1.8.5
  "@orpc/openapi": ^1.7.4
  "@orpc/server": ^1.8.5
  "@orpc/tanstack-query": ^1.8.5
  "@orpc/zod": ^1.7.4
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@vitejs/plugin-react": ^4.7.0
  ai: ^5.0.22
  better-auth: ^1.2.12
  hono: ^4.7.8
  lucide-react: ^0.525.0
  nanoid: ^5.1.5
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: 5.9.2
  typescript-result: ^3.5.2
  vite: ^7.0.5
  vitest: ^3.2.4
  wrangler: ^4.25.0
  zod: ^4.1.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "@vscode/ripgrep"
  - better-sqlite3
  - dugite
  - electron
  - electron-winstaller
  - esbuild
  - msw
  - oxc-resolver
  - sharp
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-typescript
  - unrs-resolver
  - workerd

patchedDependencies:
  conf@14.0.0: patches/conf@14.0.0.patch

sideEffectsCache: false
